plugins {
    id 'java'
}

group = 'com.mrbysco'
version = plugin_version
base {
    archivesName = "${mod_name}"
}
description = "Syncs recipes with JEI"

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${paper_version}"
    compileOnly "io.netty:netty-buffer:4.1.118.Final"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks {
    compileJava {
        options.release = 21
    }
}

processResources {
    def props = [
            plugin_version: plugin_version,
            mc_version: mc_version
    ]
    getInputs().properties(props)
    filteringCharset("UTF-8")
    filesMatching(["plugin.yml", "paper-plugin.yml"]) {
        expand(props)
    }
}
