name: JEIRecipeBridge
version: '${plugin_version}'
main: com.mrbysco.jeicompat.JEIRecipeBridgePlugin
api-version: '1.21'
author: "Mrbysco"
description: "Syncs server recipes to Fabric/NeoForge JEI clients."
website: "https://www.curseforge.com/minecraft/bukkit-plugins/jei-recipe-bridge"
folia-supported: true
